# Déploiement manuel ou quand je crée un tag de version (ex: v1.0)
workflow:
    rules:
        - if: '$CI_PIPELINE_SOURCE == "web"'
        - if: '$CI_COMMIT_TAG =~ /^v/'

stages:
    - build
    - terraform
    - deploy
    - destroy

variables:
    AWS_REGION: eu-west-3
    AWS_ROLE_ARN: arn:aws:iam::911558392127:role/deploy-gitlab
    S3_BUCKET: elasticbeanstalk-eu-west-3-911558392127
    EB_APPLICATION: les-ptits-carnets-de-schizy
    EB_ENVIRONMENT: les-ptits-carnets-de-schizy-env

build:
    stage: build
    image: composer:2
    script:
        - composer install --optimize-autoloader --no-interaction #--no-dev
        - apt-get update -y && apt-get install -y zip
        - zip -r app.zip . -x '.git/*' 'var/cache/*' 'var/log/*'
    artifacts:
        paths:
            - app.zip
        expire_in: 1 hour

terraform:
    stage: terraform
    needs:
        - build
    image:
        name: hashicorp/terraform:1.10
        entrypoint: [""]
    resource_group: terraform   # jamais deux jobs en même temps
    id_tokens:
        AWS_OIDC_TOKEN:
            aud: sts.amazonaws.com
    variables:
        AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/aws_oidc_token
    before_script:
        - echo "$AWS_OIDC_TOKEN" > "$AWS_WEB_IDENTITY_TOKEN_FILE"
    script:
        - terraform init -input=false
        - terraform validate
        - terraform apply -input=false -auto-approve

deploy:
    stage: deploy
    needs:
        - build
        - terraform
    image:
        name: amazon/aws-cli:2.15.0
        entrypoint: [""]
    # Fonctionnalité GitLab pour récupérer le token OpenID Connect à sts.amazonaws.com
    id_tokens:
        AWS_OIDC_TOKEN:
            aud: sts.amazonaws.com
    before_script:
        - echo "$AWS_OIDC_TOKEN" > /tmp/web_identity_token
        - export AWS_ROLE_ARN="$AWS_ROLE_ARN"
        - export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/web_identity_token
        - export AWS_DEFAULT_REGION="$AWS_REGION"

    script:
        - VERSION="$CI_COMMIT_SHA"
        - aws s3 cp app.zip "s3://${S3_BUCKET}/${VERSION}.zip"
        - |
            aws elasticbeanstalk create-application-version \
              --application-name "$EB_APPLICATION" \
              --version-label "$VERSION" \
              --source-bundle S3Bucket="$S3_BUCKET",S3Key="${VERSION}.zip" \
            || echo "Création de la version échouée (probablement déjà existante), on continue."
        - |
            aws elasticbeanstalk update-environment \
              --environment-name "$EB_ENVIRONMENT" \
              --version-label "$VERSION"

destroy:
    stage: destroy
    needs:
        - deploy
    image:
        name: hashicorp/terraform:1.10
        entrypoint: [""]
    resource_group: terraform
    id_tokens:
        AWS_OIDC_TOKEN:
            aud: sts.amazonaws.com
    variables:
        AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/aws_oidc_token
    before_script:
        - echo "$AWS_OIDC_TOKEN" > "$AWS_WEB_IDENTITY_TOKEN_FILE"
    script:
        - terraform init -input=false
        - terraform destroy -input=false -auto-approve

        # Vide le bucket EB - attention c'est le même bucket pour TOUTES mes app EB xD
        - aws s3 rm s3://elasticbeanstalk-eu-west-3-911558392127 --recursive
    when: manual
