name: Deploy

on:
    push:
        branches: [ main ]

permissions:
    id-token: write   # Obligatoire pour OIDC
    contents: read

jobs:
    run_job_with_aws:
        runs-on: ubuntu-latest
        steps:
            -   name: Show OIDC token claims
                run: |
                    TOKEN=$(curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
                    echo $TOKEN | cut -d'.' -f2 | base64 -d 2>/dev/null | python3 -m json.tool

    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Indispensable pour l'authentification OIDC
            contents: read  # Requis pour faire le checkout du code
        steps:
            -   uses: actions/checkout@v4
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
            -   name: Installer les dépendances
                run: composer install #--no-dev --optimize-autoloader --no-interaction
            # - name: Tests (à faire avant le --no-dev si besoin de PHPUnit)
            -   name: Créer l'archive
                run: zip -r app.zip . -x '.git/*' 'var/cache/*' 'var/log/*'
            -   uses: aws-actions/configure-aws-credentials@v4
                with:
                    role-to-assume: arn:aws:iam::911558392127:role/deploy
                    aws-region: eu-west-3

            -   name: Déployer
                run: |
                    VERSION=${{ github.sha }}
                    aws s3 cp app.zip s3://elasticbeanstalk-eu-west-3-911558392127/$VERSION.zip
                    aws elasticbeanstalk create-application-version \
                      --application-name les-ptits-carnets-de-schizy \
                      --version-label $VERSION \
                      --source-bundle S3Bucket=elasticbeanstalk-eu-west-3-911558392127,S3Key=$VERSION.zip
                    aws elasticbeanstalk update-environment \
                      --environment-name les-ptits-carnets-de-schizy-env \
                      --version-label $VERSION
