name: Pipeline

# On déploie soit manuellement soit en créant un tag qui commence par "v" (ex: v1.0)
on:
    workflow_dispatch:
    push:
        tags: ["v*"]

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        uses: ./.github/workflows/_terraform.yml

    deploy:
        needs: terraform
        uses: ./.github/workflows/_deploy.yml
